regroup tag added, more verbose error messages
ergonlabs/liquid_dart pull request #15
Opened 2021-06-05 17:14 UTC by mikes222

2021-06-07 12:48 UTC, stefanrusek requested changes
Just a couple naming issues

2021-06-07 12:48 UTC, stefanrusek commented on lib/src/buildin_tags/regroup.dart
> +extension JaggedIterable<T> on Iterable<Iterable<T>> {
Prefix name with an underscore

2021-06-07 12:48 UTC, stefanrusek commented on lib/src/exception/parseblock_exception.dart
> +class ParseblockException implements Exception {
Capital b

2021-06-07 12:48 UTC, stefanrusek commented on lib/src/exception/tagrender_exception.dart
> +class TagrenderException implements Exception {
Capital r

2021-06-14 17:12 UTC, mikes222 commented
Updated the master branch to reflect your suggestions.

2021-06-20 08:41 UTC, mikes222 commented
Do I need to do some additional things for the updated pull request?

2021-06-20 15:03 UTC, stefanrusek commented
Fix failed check. Try 'dart format -l 200' to fix the formatting

2021-06-20 15:37 UTC, mikes222 commented
done. expressions.dart has been changed (3 blank lines inserted)

2021-06-27 14:22 UTC, merged